### ISSUE TITLE
creating something similar, how did you find the condiment ids?

### ISSUE THREAD

**Issue by reteps** [4Kaylum/PyDonalds#1]
I cant find a good way of getting them.

**Comment by 4Kaylum** [comment]
This basically imitates the JSON sent by the McDonalds app - what I did here was just create some orders on the app, and when you press checkout it sends the request to a server to get the price. Using a packet capture app, or Wireshark, or something similar, you can see the request data that's being sent.

**Comment by reteps** [comment]
hey @4Kaylum would you want to collaborate with me on my version of this? I added a few more functions so mine has some added functionality.

**Comment by reteps** [comment]
https://github.com/reteps/McdonaldsOnline
