### ISSUE TITLE
Api Key

### ISSUE THREAD

**Issue by Coffee-Boyy** [4Kaylum/PyDonalds#2]
Where do I get an API key to use the API?

**Comment by reteps** [comment]
You have to sniff it using wireshark, Charles,etc

**Comment by 4Kaylum** [comment]
You'll have to get it by packet tracing, yeah.

I'm not sure how well this library will work given that their app has updated quite a bit since I made this, not that I ever made it feature complete anyway.

**Comment by reteps** [comment]
Try my McDonald’s-api repo for a more recent version

**Comment by 4Kaylum** [comment]
https://github.com/reteps/mcdonalds-api-wrapper
